from enum import StrEnum


class EventType(StrEnum):
    BROADCAST = "BROADCAST"
    MODEL_ADD = "MODEL_ADD"
    MODEL_DELETE = "MODEL_DELETE"
    MODEL_CHANGE = "MODEL_CHANGE"
    MODEL_OPERATION_ERROR = "MODEL_OPERATION_ERROR"
    MODEL_OPERATION_SUCCESS = "MODEL_OPERATION_SUCCESS"
